project: 
  type: website
  output-dir: docs
  
engine: knitr
format: 
  html:
    fig-width: 8
    fig-height: 5
    fig-align: center
    lightbox: true
    code-fold: true
    code-tools: true
    
